url: "https://www.airlinemanager.com/"
username: "your_email@example.com"
password: "YourPasswordHere"
log_level: "warn"
budget_percent:
  fuel: 75
  maintenance: 25
  marketing: 75
good_price:
  fuel: 550
  co2: 140
hubs_maintenance_limit: 3
repair_lounges: true
buy_catering_if_missing: true
catering_duration_hours: "24"
catering_amount_option: "5000"
aircraft_wear_percent: 75
aircraft_max_hours_to_check: 48
aircraft_modify_limit: 5
fuel_critical_percent: 15
cron_schedule: "*/10 * * * *"
services:
  - "company_stats"
  - "alliance_stats"
  - "claim_rewards"
  - "staff_morale"
  - "hubs"
  - "buy_fuel"
  - "marketing"
  - "ac_maintenance"
  - "depart"
timeout_seconds: 180
# Not recommended to change this option
# on systems without GUI support
chrome_headless: true
chrome_debug: true
prometheus_address: ":9150"
